---
- name: Deploy VIP
  hosts: "efw01"
  collections:
   - fortinet.fortios
  connection: httpapi
  gather_facts: False 
  #pre-tasks:
    #- include_vars: "{{ topology }}"

  vars_files:
    - keys.yaml

  tasks:
    - name: create address objects
      fortios_firewall_address:
        state: present
        #ssl_verify: False 
        #https: False
        #host: "{{ ansible_host }}"
        firewall_address:
          name: "{{ item.name  }}"                            # pb.crg.yaml; passed in from cli
          associated_interface: "{{ fortigate_params.int_interface }}"   # role vars;  
          #comment:  "{{ comment }}"                     # prompted at runtime
          subnet: "{{ item.name }}"                       # pb.crg.yaml; passed in from cli
          #list: 
            #- ip: "{{ fortigate_params.vip[0] }}"
      loop: "{{ fortigate_params.custGrpMembers }}"

    - name: Create Address group and add objects
      fortios_firewall_addrgrp:
        state: present
        #ssl_verify: False 
        #https: False
        #host: "{{ ansible_host }}"
        firewall_addrgrp:
          allow_routing: "enable"
          comment: "comment"
          name: "{{ custTag }}"
          member:  "{{ fortigate_params.custGrpMembers }}"  
            #- name: "{{ item }}" 
      #loop: "{{ fortigate_params.vip_objects }}" 

     #- name:
       #fortios_firewall_policy:
         #firewall_policy:
           #action: accept