---
- name: Transfer public key
  bigip_ssl_certificate:
    provider: " {{ provider }}"
    name: "{{ commonName }}_{{ year }}"
    state: present
    content: "{{ lookup('file' , './certificates/{{ commonName }}_crt.crt' }}"

- name: Transfer private key
  bigip_ssl_certificate:
    provider: " {{ provider }}"
    name: "{{ commonName }}_{{ year }}"
    state: present
    content: "{{ lookup('file' , './certificates/{{ commonName }}_key.key' }}"

  

