########### module documentation links############
# https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_firewall_policy_module.html
# https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_firewall_addrgrp_module.html
# https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_firewall_address_module.html
# https://docs.ansible.com/ansible/2.9_ja/modules/fortios_address_module.html

- name: create address objects
  fortios_firewall_address:
    state: present
    ssl_verify: False 
    host: "{{ ansible_host }}"
    firewall_address:
      name: "{{  }}"                               # pb.crg.yaml; passed in from cli
      associated_interface: "{{ lb_interface }}"   # role vars;  
      comment:  "{{ comment }}"                    # prompted at runtime
      subnet: "{{  }}"                             # pb.crg.yaml; passed in from cli
      
- name: Create Address group and add objects
  fortios_firewall_addrgrp:
    firewall_addrgrp:
      allow_routing: "enable"
      comment: "comment"
      member:
        - name: "{{ some_member_name }}"
- name:
  fortios_firewall_policy:
    firewall_policy:
      action: accept
