---
- name: Create Nodes
  bigip_node:
    provider: "{{ provider }}"        # Provider DICT in group_vars/all.yaml; arguments collected at runtime
    name: "{{ item }}"                # passed in as '-e', e.g. 'ansible-playbook pb.crg.yaml -e @pb.crg.extra-vars.yaml'
    fqdn: "{{ item }}"                # passed in as '-e', e.g. 'ansible-playbook pb.crg.yaml -e @pb.crg.extra-vars.yaml'
    validate_certs: no
  loop: "{{ application_nodes.fqdn }}"     # passed in as '-e', e.g. 'ansible-playbook pb.crg.yaml -e @pb.crg.extra-vars.yaml'


- name: Create application/service Pool    
  bigip_pool:
    provider: "{{ provider }}"
    state: present
    name: "{{ pool }}"                 # passed in as '-e', e.g. 'ansible-playbook pb.crg.yaml -e @pb.crg.extra-vars.yaml'
    lb_method: "{{ lb_method }}"       # role default: round-robin, roles/https-application/defaults/main.yaml; override via extra-vars or role_vars
    monitors: " {{ monitors }}"        # role default: ['tcp', 'http']; override via extra-vars or role_vars


- name: Add Application Servers to Application/service Pool
  bigip_pool_member:
    provider: "{{ provider }}"
    pool: "{{ pool }}"
    fqdn: "{{ item }}"
    port: "{{ svc_port }}"
  loop: "{{ application_nodes.fqdn }}"


- name: Create SSL Profile 
  bigip_profile_client_ssl:
    provider: "{{ provider }}"
    state: present
    #delegate_to: localhost
    name: ot2.dev.apigee.otxlab.net_2020
    cert_key_chain:
      - cert: ot2.dev.apigee.otxlab.net_2020
        key: ot2.dev.apigee.otxlab.net_2020
        chain: ot2_dev_chain_2020

- name: Create Virtual Server
  bigip_virtual_server:
    provider: "{{ provider }}"
    name: ot2.dev.apigee.otxlab.net
    type: standard
    source: 0.0.0.0/0
    destination: 10.9.198.5
    port: 443
    pool: ot2.dev.apigee.otxlab.net
    snat: automap
    profiles:
      - tcp
      - name: ot2.dev.apigee.otxlab.net_2020
        context: client-side
    enabled_vlans: /Common/external
  delegate_to: localhost